const wordData = [
{ word: "貼紙", meaning: "sticker", example: "妹妹把貼紙貼滿了她的筆記本。(My little sister covered her notebook with stickers.)" },
{ word: "貼", meaning: "to stick; to paste", example: "請把這張海報貼在牆上。(Please stick this poster on the wall.)" },
{ word: "豆漿", meaning: "soy milk", example: "很多台灣人早上會喝豆漿。(Many Taiwanese people drink soy milk in the morning.)" },
{ word: "盒子", meaning: "box", example: "這個盒子裡放了很多小禮物。(There are many small gifts inside this box.)" },
{ word: "店員", meaning: "store clerk", example: "店員很親切，幫我找到想買的書。(The store clerk was friendly and helped me find the book I wanted.)" },
{ word: "差", meaning: "bad; poor", example: "這家店的服務有點差。(The service in this shop is a bit poor.)" },
{ word: "娃娃", meaning: "doll", example: "她從小就很喜歡收集娃娃。(She has loved collecting dolls since she was young.)" },
{ word: "它", meaning: "it", example: "我有一隻小狗，我每天都帶它去散步。(I have a puppy, and I walk it every day.)" },
{ word: "滿", meaning: "full", example: "教室裡坐得滿滿的。(The classroom is completely full.)" },
{ word: "連", meaning: "even (for emphasis)", example: "太忙了，我連午餐都沒時間吃。(I was so busy I didn’t even have time for lunch.)" },
{ word: "得到", meaning: "to get; to obtain", example: "她努力工作，得到大家的肯定。(She worked hard and received everyone’s recognition.)" },
{ word: "那樣", meaning: "like that; that way", example: "不要學他那樣說話，會讓人誤會。(Don’t speak like that, it may cause misunderstanding.)" },
{ word: "海報", meaning: "poster", example: "牆上貼著一張新的電影海報。(A new movie poster is on the wall.)" },
{ word: "吸引", meaning: "to attract", example: "這家店的設計很特別，吸引很多客人。(The shop’s design is special and attracts many customers.)" },
{ word: "商人", meaning: "businessperson; merchant", example: "古代的商人常常要到不同城市做生意。(In ancient times, merchants often traveled to different cities to do business.)" },
{ word: "心理", meaning: "psychology; mindset", example: "他買東西時常受心理影響，容易衝動消費。(He is easily influenced by his mindset and buys impulsively.)" },
{ word: "尺", meaning: "ruler", example: "請用尺量一下這張紙的長度。(Please use a ruler to measure the length of this paper.)" },
{ word: "牙刷", meaning: "toothbrush", example: "記得每天更換牙刷，保持口腔清潔。(Remember to change your toothbrush regularly.)" },
{ word: "卡通人物", meaning: "cartoon character", example: "這個文具上都是小朋友喜歡的卡通人物。(These stationery items have cartoon characters that children love.)" },
{ word: "喜愛", meaning: "to like; to be fond of", example: "他特別喜愛旅行，每年都會出國。(He loves traveling and goes abroad every year.)" },
{ word: "只好", meaning: "can only; have to", example: "下雨了，我們只好改天再去公園。(It started to rain, so we could only go to the park another day.)" },
{ word: "花", meaning: "to spend (money/time)", example: "她為了這次旅行花了很多時間準備。(She spent a lot of time preparing for this trip.)" },
{ word: "開始", meaning: "to begin", example: "電影快開始了，請大家就座。(The movie is about to begin. Please take your seats.)" },
{ word: "為了", meaning: "for; in order to", example: "他為了家人努力工作。(He works hard for his family.)" },
{ word: "顧客", meaning: "customer", example: "這家店非常重視顧客的意見。(This store values customers' opinions.)" },
{ word: "變成", meaning: "to become", example: "下雨後，路邊的水變成了一小片水池。(After the rain, the roadside puddle became a small pool.)" },
{ word: "所有", meaning: "all", example: "所有學生都要參加這次活動。(All students must participate in this activity.)" },
{ word: "這樣", meaning: "like this; this way", example: "你這樣做會更方便。(Doing it this way will be more convenient.)" },
{ word: "類", meaning: "type; category", example: "這類產品最近很受歡迎。(This type of product has become very popular recently.)" },
{ word: "影響", meaning: "to influence; impact", example: "手機使用太久會影響視力。(Using a phone too long can affect your eyesight.)" },
{ word: "增加", meaning: "to increase", example: "為了安全，學校增加了晚上的巡邏。(For safety, the school increased night patrols.)" },
{ word: "紀念", meaning: "to commemorate; souvenir", example: "我買了一個鑰匙圈當作旅行的紀念。(I bought a keychain as a souvenir from the trip.)" }

];


