const wordData = [
{ word: "贴纸", meaning: "sticker", example: "妹妹把贴纸贴满了她的笔记本。(My little sister covered her notebook with stickers.)" },
{ word: "贴", meaning: "to stick; to paste", example: "请把这张海报贴在墙上。(Please stick this poster on the wall.)" },
{ word: "豆浆", meaning: "soy milk", example: "很多台湾人早上会喝豆浆。(Many Taiwanese people drink soy milk in the morning.)" },
{ word: "盒子", meaning: "box", example: "这个盒子里放了很多小礼物。(There are many small gifts inside this box.)" },
{ word: "店员", meaning: "store clerk", example: "店员很亲切，帮我找到想买的书。(The store clerk was friendly and helped me find the book I wanted.)" },
{ word: "差", meaning: "bad; poor", example: "这家店的服务有点差。(The service in this shop is a bit poor.)" },
{ word: "娃娃", meaning: "doll", example: "她从小就很喜欢收集娃娃。(She has loved collecting dolls since she was young.)" },
{ word: "它", meaning: "it", example: "我有一只小狗，我每天都带它去散步。(I have a puppy, and I walk it every day.)" },
{ word: "满", meaning: "full", example: "教室里坐得满满的。(The classroom is completely full.)" },
{ word: "连", meaning: "even (for emphasis)", example: "太忙了，我连午餐都没时间吃。(I was so busy I didn’t even have time for lunch.)" },
{ word: "得到", meaning: "to get; to obtain", example: "她努力工作，得到大家的肯定。(She worked hard and received everyone’s recognition.)" },
{ word: "那样", meaning: "like that; that way", example: "不要学他那样说话，会让人误会。(Don’t speak like that, it may cause misunderstanding.)" },
{ word: "海报", meaning: "poster", example: "墙上贴着一张新的电影海报。(A new movie poster is on the wall.)" },
{ word: "吸引", meaning: "to attract", example: "这家店的设计很特别，吸引很多客人。(The shop’s design is special and attracts many customers.)" },
{ word: "商人", meaning: "businessperson; merchant", example: "古代的商人常常要到不同城市做生意。(In ancient times, merchants often traveled to different cities to do business.)" },
{ word: "心理", meaning: "psychology; mindset", example: "他买东西时常受心理影响，容易冲动消费。(He is easily influenced by his mindset and buys impulsively.)" },
{ word: "尺", meaning: "ruler", example: "请用尺量一下这张纸的长度。(Please use a ruler to measure the length of this paper.)" },
{ word: "牙刷", meaning: "toothbrush", example: "记得每天更换牙刷，保持口腔清洁。(Remember to change your toothbrush regularly.)" },
{ word: "卡通人物", meaning: "cartoon character", example: "这个文具上都是小朋友喜欢的卡通人物。(These stationery items have cartoon characters that children love.)" },
{ word: "喜爱", meaning: "to like; to be fond of", example: "他特别喜爱旅行，每年都会出国。(He loves traveling and goes abroad every year.)" },
{ word: "只好", meaning: "can only; have to", example: "下雨了，我们只好改天再去公园。(It started to rain, so we could only go to the park another day.)" },
{ word: "花", meaning: "to spend (money/time)", example: "她为了这次旅行花了很多时间准备。(She spent a lot of time preparing for this trip.)" },
{ word: "开始", meaning: "to begin", example: "电影快开始了，请大家就座。(The movie is about to begin. Please take your seats.)" },
{ word: "为了", meaning: "for; in order to", example: "他为了家人努力工作。(He works hard for his family.)" },
{ word: "顾客", meaning: "customer", example: "这家店非常重视顾客的意见。(This store values customers' opinions.)" },
{ word: "变成", meaning: "to become", example: "下雨后，路边的水变成了一小片水池。(After the rain, the roadside puddle became a small pool.)" },
{ word: "所有", meaning: "all", example: "所有学生都要参加这次活动。(All students must participate in this activity.)" },
{ word: "这样", meaning: "like this; this way", example: "你这样做会更方便。(Doing it this way will be more convenient.)" },
{ word: "类", meaning: "type; category", example: "这类产品最近很受欢迎。(This type of product has become very popular recently.)" },
{ word: "影响", meaning: "to influence; impact", example: "手机使用太久会影响视力。(Using a phone too long can affect your eyesight.)" },
{ word: "增加", meaning: "to increase", example: "为了安全，学校增加了晚上的巡逻。(For safety, the school increased night patrols.)" },
{ word: "纪念", meaning: "to commemorate; souvenir", example: "我买了一个钥匙圈当作旅行的纪念。(I bought a keychain as a souvenir from the trip.)" }
];
